server:
  port: 8888
spring:
  application:
    name: base-framework

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}

      # 命令超时（Duration）
      timeout: ${REDIS_TIMEOUT:10s}

      lettuce:
        pool:
          # 最大活跃连接数（>0 即启用池）
          max-active: ${REDIS_POOL_MAX_ACTIVE:8}
          max-idle: ${REDIS_POOL_MAX_IDLE:8}
          min-idle: ${REDIS_POOL_MIN_IDLE:0}
          # -1 表示无限等待；建议生产给一个上限
          max-wait: ${REDIS_POOL_MAX_WAIT:-1ms}


app:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3307/app
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3307/analytics
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

calcite:
  primary:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/app
    username: root
    password: 123456
  secondary:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/analytics
    username: root
    password: 123456



sa-token:
  token-name: satoken
  timeout: 86400
  is-concurrent: true
  is-share: true
  token-style: uuid
