server:
  port: 8888

spring:
  application:
    name: base-framework
  data:
    redis:
      #基础配置
      host: ${REDIS_HOST:localhost}
      port: ${redis_port:6379}

      #连接池配置
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms


app:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3307/app
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3307/analytics
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

calcite:
  primary:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/app
    username: root
    password: 123456
  secondary:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/analytics
    username: root
    password: 123456



sa-token:
  token-name: satoken
  timeout: 86400
  is-concurrent: true
  is-share: true
  token-style: uuid
